# Generated by Django 5.0.6 on 2024-05-09 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица')),
                ('house_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер дома')),
                ('supplier_debt', models.FloatField(default=0, verbose_name='Задолженность перед поставщиком')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Создан')),
                ('entrepreneur_supplier', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.entrepreneur', verbose_name='Поставщик (ИП)')),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица')),
                ('house_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер дома')),
                ('supplier_debt', models.FloatField(default=0, verbose_name='Задолженность перед поставщиком')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Создан')),
                ('entrepreneur_supplier', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.entrepreneur', verbose_name='Поставщик (ИП)')),
                ('factory_supplier', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.factory', verbose_name='Поставщик (завод)')),
            ],
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='factory_supplier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.factory', verbose_name='Поставщик (завод)'),
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица')),
                ('house_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер дома')),
                ('supplier_debt', models.FloatField(default=0, verbose_name='Задолженность перед поставщиком')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Создан')),
                ('entrepreneur_supplier', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.entrepreneur', verbose_name='Поставщик (ИП)')),
                ('factory_supplier', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.factory', verbose_name='Поставщик (завод)')),
                ('retailer_supplier', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.retailer', verbose_name='Поставщик (розничная сеть)')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='')),
                ('version', models.IntegerField(verbose_name='')),
                ('market_access_date', models.DateField(auto_now_add=True, verbose_name='')),
                ('entrepreneur_owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.entrepreneur', verbose_name='')),
                ('factory_owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.factory', verbose_name='')),
                ('retailer_owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.retailer', verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='factory',
            name='retailer_supplier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.retailer', verbose_name='Поставщик (розничная сеть)'),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='retailer_supplier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.retailer', verbose_name='Поставщик (розничная сеть)'),
        ),
    ]
