# Generated by Django 5.0.6 on 2024-05-09 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_entrepreneur_owner_factory_owner_product_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='entrepreneur_supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.entrepreneur', verbose_name='Поставщик (ИП)'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='factory_supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.factory', verbose_name='Поставщик (завод)'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='retailer_supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.retailer', verbose_name='Поставщик (розничная сеть)'),
        ),
    ]
