# Generated by Django 5.0.6 on 2024-05-10 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_factory_entrepreneur_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrepreneur',
            name='entrepreneur_supplier',
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='factory_supplier',
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='retailer_supplier',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='entrepreneur_supplier',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='factory_supplier',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='retailer_supplier',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='entrepreneur_supplier',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='factory_supplier',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='retailer_supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='entrepreneur_supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='main.entrepreneur', verbose_name='Поставщик (ИП)'),
        ),
        migrations.AddField(
            model_name='product',
            name='factory_supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='main.factory', verbose_name='Поставщик (завод)'),
        ),
        migrations.AddField(
            model_name='product',
            name='retailer_supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='main.retailer', verbose_name='Поставщик (розничная сеть)'),
        ),
    ]
