# Generated by Django 5.0.6 on 2024-05-10 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_entrepreneur_entrepreneur_supplier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrepreneur',
            options={'verbose_name': 'Entrepreneur', 'verbose_name_plural': 'Entrepreneurs'},
        ),
        migrations.AlterModelOptions(
            name='factory',
            options={'verbose_name': 'Factory', 'verbose_name_plural': 'Factories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='retailer',
            options={'verbose_name': 'Retailer', 'verbose_name_plural': 'Retailers'},
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='product',
            name='entrepreneur_owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.entrepreneur', verbose_name='Владелец (ИП)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='factory_owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.factory', verbose_name='Владелец (завод)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='market_access_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата выхода на рынок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='product',
            name='retailer_owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.retailer', verbose_name='Владелец (розничная сеть)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='version',
            field=models.IntegerField(verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
