# Generated by Django 5.0.6 on 2024-05-11 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_entrepreneur_options_alter_factory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrepreneur',
            old_name='supplier_debt',
            new_name='total_supplier_debt',
        ),
        migrations.RenameField(
            model_name='factory',
            old_name='supplier_debt',
            new_name='total_supplier_debt',
        ),
        migrations.RenameField(
            model_name='retailer',
            old_name='supplier_debt',
            new_name='total_supplier_debt',
        ),
    ]
